#!/usr/bin/python

'''Create tables in the PostgreSQL database'''
commands = [
	"""
	CREATE TABLE _2018_team_target_summary (
		team text,
		_11J_ETJ numeric,
		_11K_ETK numeric,
		_11N numeric,
		_11H numeric
	)
	""",
	"""
	CREATE TABLE activity_pattern_enrolled(
		unit_delivery_team text,
		funding_source text,
		enrol_week numeric,
		sum_of_enrol_ahc numeric
	)
	""",
	"""
	CREATE TABLE activity_pattern_enrolled_funded (
		unit_delivery_team text,
		funding_source text,
		enrol_week numeric,
		sum_of_enrol_ahc numeric
	)
	""",
	"""
	CREATE TABLE activity_pattern_enrolled_unfunded (
		unit_delivery_team text,
		funding_source text,
		enrol_week numeric,
		sum_of_enrol_ahc numeric	
	)
	""",
	"""
	CREATE TABLE activity_pattern_resulted (
		unit_delivery_team text,
		funding_source text,
		result_week numeric,
		sum_of_resulted_ahc numeric	
	)
	""",
	"""
	CREATE TABLE activity_pattern_resulted_funded (
		unit_delivery_team text,
		funding_source text,
		result_week numeric,
		sum_of_resulted_ahc numeric
	)
	""",
	"""
	CREATE TABLE activity_pattern_resulted_unfunded (
		unit_delivery_team text,
		funding_source text,
		result_week numeric,
		sum_of_resulted_ahc numeric	
	)
	""",
	"""
	CREATE TABLE activity_pattern_trend (
		unit_delivery_team text,
		division text,
		funding_source text,
		week_2018 numeric,
		week_2017 numeric,
		target_2018 numeric,
		target_2017 numeric,
		enrolled_2018 numeric,
		resulted_2018 numeric,
		funded_enrolled_2018 numeric,
		funded_resulted_2018 numeric,
		unfunded_enrolled_2018 numeric,
		unfunded_resulted_2018 numeric,
		enrolled_2017 numeric,
		resulted_2017 numeric,
		funded_enrolled_2017 numeric,
		funded_resulted_2017 numeric,
		unfunded_enrolled_2017 numeric,
		unfunded_resulted_2017 numeric
	)
	""",
	"""
	CREATE TABLE age_highest_school_completed (
		course_admin_team text,
		delivery_location_team text,
		teaching_period text,
		student_id text,
		deceased_indicator text,
		atsi text,
		student_last_name text,
		student_first_name text,
		student_gender text,
		student_dob date,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		disability_flag text,
		home_language_code text,
		birth_country_code text
	)
	""",
	"""
	CREATE TABLE apprentice_course (
		course_admin_team text,
		student_id text,
		atsi text,
		age_range text,
		disability_flag text,
		employment_category text,
		employment_category_description text,
		residential_postcode text,
		highest_school_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		country_of_birth text,
		language text,
		highest_prior_education_level_completed text,
		at_school_indicator text,
		industry text,
		foe2 text,
		foe4 text,
		course_level_description text,
		course_code text,
		course_name text,
		unit_funding_source text,
		tci text,
		tci_start_date text,
		tci_end_date text,
		sum_of_enrolled_ahc numeric,
		sum_of_resulted_ahc numeric,
		address_start_date text,
		address_end_date text,
		employer_or_business_name text,
		employer_address_line_1 text,
		employer_address_line_2 text,
		employer_suburb text,
		employer_state text,
		employer_postcode text,
		employer_phone_number text,
		employer_fax_number text,
		employer_contact_name text,
		employer_email_details text
	)
	""",
	"""
	CREATE TABLE apprentice_mega (
		delivery_location_team text,
		course_admin_team text,
		student_id text,
		atsi text,
		age numeric,
		age_range text,
		disability_flag text,
		employment_category text,
		employment_status_description text,
		residential_postcode text,
		highest_school_level_completed_code text,
		school_level_description text,
		highest_school_level_completed_year text,
		birth_country_code text,
		birth_country_name text,
		home_language_code text,
		home_language_name text,
		highest_prior_education_level_completed_code text,
		prior_education_level text,
		at_school_indicator text,
		vet_in_school_indicator text,
		course_industry text,
		course_industry_description text,
		foe2_description text,
		foe4_description text,
		course_level text,
		course_level_description text,
		course_code text,
		course_name text,
		unit_code text,
		unit_name text,
		unit_funding_source text,
		grade text,
		unit_delivery_location text,
		enrol_date date,
		result_date date,
		outcome text,
		fee_category text,
		enrolled_ahc numeric,
		resulted_ahc numeric,
		api_id text,
		api_start_date text,
		api_end_date text,
		addr_type text,
		addr_start_date text,
		addr_end_date text,
		addr_line1 text,
		addr_line2 text,
		addr_line3 text,
		addr_line4 text,
		addr_line5 text,
		addr_aust_pc text,
		phone_1 text,
		phone_2 text,
		phone_3 text,
		other_details text
	)
	""",
	"""
	CREATE TABLE apprentice_sua (
		delivery_location_team text,
		student_id text,
		atsi text,
		age_range text,
		disability_flag text,
		employment_category text,
		employment_category_description text,
		residential_postcode text,
		highest_school_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		country_of_birth text,
		language text,
		highest_prior_education_level_completed text,
		at_school_indicator text,
		vet_in_school_indicator text,
		course_industry text,
		course_industry_name text,
		foe2 text,
		foe4 text,
		course_level_description text,
		course_code text,
		unit_code text,
		fee_catagory text,
		unit_funding_source text,
		grade text,
		unit_delivery_location text,
		enrol_date date,
		result_date date,
		tci text,
		tci_start_date text,
		tci_end_date text,
		enrolled_ahc numeric,
		resulted_ahc numeric
	)
	""",
	"""
	CREATE TABLE error_2018_not_reported_tls_tl0_douglas (
		teaching_period text,
		course_admin_team text,
		student_id text,
		unit_funding_source text,
		course_code text,
		fee_catagory text,
		unit_code text,
		override_activity_start_date date,
		course_commencement_date date
	)
	""",
	"""
	CREATE TABLE error_possible_act_end_dt_errors_douglas (
		course_admin_team text,
		student_id text,
		student_first_name text,
		student_last_name text,
		course_code text,
		unit_code text,
		teaching_period text,
		grade text,
		enrolment_activity_end_date date,
		cancelled_date date,
		granted_date date,
		result_date date,
		disc_date date,
		unit_census_date date
	)
	""",
	"""
	CREATE TABLE error_possible_act_st_dt_errors_douglas (
		course_admin_team text,
		student_id text,
		course_code text,
		unit_code text,
		teaching_period text,
		enrol_date date,
		override_activity_start_date date,
		unit_census_date date
	)
	""",
	"""
	CREATE TABLE error_possible_student_dups_douglas (
		error_msg text,
		student_id text,
		student_first_name text,
		student_last_name text,
		dob date,
		student_gender text,
		atsi text,
		disability_flag text,
		residential_postcode text,
		country_of_birth text,
		language text,
		highest_school_level_completed_year text,
		highest_school_level_completed text
	)
	""",
	"""
	CREATE TABLE error_possible_student_dups_douglas_2017 (
		error_msg text,
		student_id_2018 text,
		student_first_name_2018 text,
		student_last_name_2018 text,
		dob_2018 date,
		student_id_2017 text,
		student_first_name_2017 text,
		student_last_name_2017 text,
		dob_2017 date
	)
	""",
	"""
	CREATE TABLE error_vfh_enrolments_by_vet_teams (
		error_type text,
		course_admin_team text,
		teaching_period text,
		student_id text,
		course_code text,
		unit_code text,
		unit_delivery_location text,
		unit_delivery_remoteness text,
		unit_funding_source text,
		fee_category text,
		grade text,
		administrative_unit_status text,
		chessn text,
		vet_stats_atsi text,
		vfh_atsi_code text,
		vfh_citizenship_code text,
		vfh_birth_country_code text,
		vfh_home_language_code text,
		vfh_term_location_postcode text,
		vfh_term_location_country_code text,
		vfh_home_location_postcode text,
		vfh_home_location_country_code text,
		vfh_arrival_year text,
		vfh_permanent_resident_code text,
		vfh_commencing_location_postcode text,
		vfh_commencing_geographic_location text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_year text,
		basis_for_admission_code text,
		hecs_payment_option_code text,
		unit_student_status_code text,
		enrol_date date,
		unit_census_date date
	)
	""",
	"""
	CREATE TABLE errors_2017_comp_or_ur_ce_2018_reenrolled_douglas_to_check (
		delivery_location_team_2018 text,
		student_id text,
		student_first_name text,
		student_last_name text,
		course_code_2017 text,
		weekly_2017_unit_code text,
		grade_2017 text,
		result_date_2017 date,
		weekly_2017_unit_funding_source text,
		course_code_2018 text,
		weekly_current_unit_code text,
		grade_2018 text,
		result_date_2018 date,
		weekly_current_unit_funding_source text
	)
	""",
	"""
	CREATE TABLE errors_aci_tci_not_k_margaret_to_check (
		delivery_location_team text,
		student_id text,
		course_code text,
		fee_category text,
		unit_funding_source text,
		aci text,
		tci text
	)
	""",
	"""
	CREATE TABLE errors_for_correction_by_vet_stats_officer (
		error_type text,
		course_admin_team text,
		delivery_location_team text,
		teaching_period text,
		student_id text,
		student_last_name text,
		student_first_name text,
		atsi text,
		gender text,
		dob date,
		deceased_indicator text,
		disability text,
		home_language_code text,
		birth_country_code text,
		residential_post_code text,
		home_state text,
		prior_education text,
		employment_category text,
		at_school_indicator text,
		vet_in_school_indicator text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		age_highest_school_completed text,
		course_code text,
		unit_code text,
		unit_funding_source text,
		enrol_date date,
		outcome text,
		unit_attempt_status text,
		study_reason text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		no_course_intention text,
		total_lrnsupp_ahc text,
		total_enrolled_ahc text,
		granted_date date,
		cancelled_date date,
		not_approved_date date,
		usi_flag text,
		entitlement_contract_description text,
		course_commencement_date date,
		course_attempt_status text
	)
	""",
	"""
	CREATE TABLE errors_for_correction_by_vet_teams (
		error_type text,
		course_admin_team text,
		delivery_location_team text,
		teaching_period text,
		student_id text,
		student_last_name text,
		student_first_name text,
		atsi text,
		gender text,
		dob date,
		deceased_indicator text,
		disability text,
		home_language_code text,
		birth_country_code text,
		residential_post_code text,
		home_state text,
		prior_education text,
		employment_category text,
		at_school_indicator text,
		vet_in_school_indicator text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		age_highest_school_completed text,
		course_code text,
		unit_code text,
		unit_funding_source text,
		enrol_date date,
		outcome text,
		unit_attempt_status text,
		study_reason text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		no_course_intention text,
		total_lrnsupp_ahc text,
		total_enrolled_ahc text,
		granted_date date,
		cancelled_date date,
		not_approved_date date,
		usi_flag text,
		entitlement_contract_description text,
		course_commencement_date date,
		course_attempt_status text
	)
	""",
	"""
	CREATE TABLE errors_for_correction_by_vet_teams_course_intention (
		error_type text,
		course_admin_team text,
		delivery_location_team text,
		teaching_period text,
		student_id text,
		student_last_name text,
		student_first_name text,
		atsi text,
		gender text,
		dob text,
		deceased_indicator text,
		disabiltiy text,
		home_language_code text,
		birth_country_code text,
		residential_post_code text,
		home_state text,
		prior_education text,
		employment_category text,
		at_school_indicator text,
		vet_in_school_indicator text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		age_highest_school_completed text,
		course_code text,
		unit_code text,
		unit_funding_source text,
		enrol_date date,
		outcome text,
		unit_attempt_status text,
		study_reason text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		no_course_intention text,
		total_lrnsupp_ahc text,
		total_enrolled_ahc text,
		granted_date date,
		cancelled_date date,
		not_approved_date date,
		usi_flag text,
		entitlement_contract_description text,
		course_commencement_date date,
		course_attempt_status text
	)
	""",
	"""
	CREATE TABLE errors_inconsistent_fees_and_funding_sources_douglas (
		teaching_period text,
		delivery_location_team text,
		unit_delivery_location text,
		remoteness text,
		student_id text,
		vet_school_name text,
		course_code text,
		unit_funding_source text,
		fee_category text,
		correspondence_category text,
		vet_in_school_indicator text,
		at_school_indicator text,
		staff_indicator text,
		postal_postcode text,
		student_home_state text
	)
	""",
	"""
	CREATE TABLE errors_k_no_current_or_missing_aci_tci_margaret_to_check (
		delivery_location_team text,
		student_id text,
		course_code text,
		course_attempt_status text,
		fee_category text,
		unit_funding_source text,
		current_tci text,
		current_aci text,
		previous_tci_code text,
		previous_tci_start_dte text,
		previous_tci_end_dte text
	)
	""",
	"""
	CREATE TABLE errors_sua_duplicates_douglas_to_check (
		delivery_location_team text,
		student_id text,
		unit_code text,
		unit_attempt_status text,
		teaching_period text,
		grade text,
		enrol_date date,
		override_activity_start_date date,
		result_date date,
		enrolment_activity_end_date date,
		course_code text,
		unit_funding_source text
	)
	""",
	"""
	CREATE TABLE errors_sua_duplicates_douglas_to_check_checked (
		delivery_location_team text,
		student_id text,
		unit_code text,
		unit_attempt_status text,
		teaching_period text,
		grade text,
		enrol_date date,
		override_activity_start_date date,
		result_date date,
		enrolment_activity_end_date date,
		course_code text,
		unit_funding_source text,
		start_date date,
		end_date date,
		status text
	)
	""",
	"""
	CREATE TABLE errors_sua_result_before_start_dt_douglas (
		delivery_location_team text,
		student_id text,
		unit_code text,
		unit_attempt_status text,
		teaching_period text,
		grade text,
		enrol_date date,
		override_activity_start_date date,
		result_date date,
		enrolment_activity_end_date date,
		course_code text,
		unit_funding_source text
	)
	""",
	"""
	CREATE TABLE errors_superseded_units_douglas (
		course_admin_team text,
		student_id text,
		unit_code text,
		related_unit text,
		course_code text,
		override_activity_start_date date,
		result_date date,
		override_activity_end_date date,
		grade text,
		teaching_period text,
		unit_code_description text
	)
	""",
	"""
	CREATE TABLE errors_w_graded_vfh_sua_douglas_to_check (
		delivery_location_team text,
		student_id text,
		student_first_name text,
		student_last_name text,
		course_code text,
		course_name text,
		unit_code text,
		teaching_period text,
		grade text,
		unit_delivery_location text,
		enrol_date date,
		enrolment_activity_end_date date,
		disc_date date
	)
	""",
	"""
	CREATE TABLE errors_wf_graded_sua_douglas_to_check (
		delivery_location_team text,
		student_id text,
		student_first_name text,
		student_last_name text,
		course_code text,
		unit_code text,
		teaching_period text,
		grade text,
		unit_delivery_location text,
		enrol_date date,
		enrolment_activity_end_date date
	)
	""",
	"""
	CREATE TABLE etp_activity (
		division text,
		unit_delivery_team text,
		course_code text,
		number_of_units_to_complete numeric,
		target_sca numeric,
		successful_ahc numeric,
		funded_enrolled_sca numeric,
		funded_enrolled_ahc numeric,
		team_target_ahc numeric
	)
	""",
	"""
	CREATE TABLE prior_yr_ce (
		training_organisation_delivery_location_identifier text,
		client_identifier text,
		module_unit_of_competency_identifier text,
		qualification_course_identifier text,
		enrolment_activity_start_date text,
		enrolment_activity_end_date text,
		delivery_mode_identifier text,
		outcome_identifier_national text,
		scheduled_hours text,
		funding_source_national text,
		commencing_course_identifier text,
		training_contract_identifier_new_apprenticeships text,
		client_identifier_new_apprenticeships text,
		study_reason_identifier text,
		vet_in_schools_flag text,
		outcome_identifier_training_organisation text,
		funding_source_state_training_authority text,
		client_tutition_fee text,
		fee_exemption_concession_type_identifier text,
		purchasing_contract_identifier text,
		purchasing_contract_schedule_identifier text,
		hours_attended text,
		specific_program_identifier text,
		teaching_period text,
		admin_location text,
		approved text,
		course_original text,
		funding_original text,
		study_reason_original text,
		course_commencement_date date,
		course_attempt_status text,
		vet_school text,
		commencing_course_identifier_original text
	)
	""",
	"""
	CREATE TABLE q532b_distinct_funded_enrolled_etp_headcount (
		division text,
		description text,
		student_id text,
		course_code text
	)
	""",
	"""
	CREATE TABLE q532c_count_distinct_funded_enrolled_etp_sca (
		divsion text,
		description text,
		course_code text,
		count_of_student_id numeric
	)
	""",
	"""
	CREATE TABLE q534a_successful_etp_ahc (
		divsion text,
		description text,
		course_code text,
		successful_ahc_ca_rpl numeric	
	)
	""",
	"""
	CREATE TABLE sca_enrolled_ahc_calculation (
		student_id text,
		course_code text,
		sca_funding_source text,
		sum_of_enrolled_ahc numeric
	)
	""",
	"""
	CREATE TABLE sca_resulted_ahc_calculation (
		student_id text,
		course_code text,
		sca_funding_source text,
		sum_of_resulted_ahc numeric
	)
	""",
	"""
	CREATE TABLE student (
		a_ses2006 text,
		age numeric,
		age_range text,
		atsi text,
		chessn text,
		country_of_birth text,
		deceased_indicator text,
		disability_flag text,
		dob date,
		email_address text,
		employment_category text,
		enrolled_ahc_ex_ns_ct_sw numeric,
		equivalent_eftsl numeric,
		ft_pt_status text,
		highest_prior_education_level_completed text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		language text,
		mobile_phone_number text,
		postal_postcode text,
		residential_postcode text,
		resulted_ahc_ex_ns_ct_sw numeric,
		student_first_name text,
		student_gender text,
		student_home_state text,
		student_id text,
		student_last_name text,
		usi_flag text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE student_enrolled_ahc_calculation (
		student_id text,
		sum_of_enrolled_ahc numeric
	)
	""",
	"""
	CREATE TABLE student_resulted_ahc_calculation (
		student_id text,
		sum_of_resulted_ahc numeric
	)
	""",
	"""
	CREATE TABLE student_course_attempt (
		a_ses2006 text,
		age numeric,
		age_range text,
		at_school_indicator text,
		atsi text,
		basis_for_admission text,
		basis_for_admission_code text,
		birth_country text,
		chessn text,
		contract_team text,
		correspondence_category text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_name text,
		course_requirements_completed_date date,
		course_requirements_completed_indicator text,
		deceased_indicator text,
		division text,
		email_address text,
		enrolled_ahc_ex_ns_ct_sw numeric,
		entitlement_contract_description text,
		fee_category text,
		foe2 text,
		foe4 text,
		hecs_payment_option text,
		hecs_payment_option_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		industry text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		level text,
		mobile_phone_number text,
		no_course_intention text,
		postal_postcode text,
		residential_postcode text,
		resulted_ahc_ex_ns_ct_sw numeric,
		sca_funding_source text,
		student_gender text,
		student_home_state text,
		student_id text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE student_unit_attempt (
		a_ses2006 text,
		aci text,
		administrative_unit_status text,
		age numeric,
		at_school_indicator text,
		atsi text,
		basis_for_admission text,
		basis_for_admission_code text,
		birth_country_code text,
		cancelled_date date,
		chessn text,
		contract text,
		contract_course_unit_code text,
		contract_course_unit_name text,
		contract_team text,
		correspondence_category text,
		country_of_birth text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_industry text,
		course_industry_name text,
		course_name text,
		course_requirements_completed_date date,
		course_requirements_completed_indicator text,
		deceased_indicator text,
		delivery_location_team text,
		delivery_postal_location text,
		delivery_providence text,
		delivery_region text,
		delivery_remoteness text,
		delivery_state_code text,
		disability_flag text,
		disc_date date,
		division text,
		email_address text,
		employment_category text,
		employment_category_description text,
		enrol_date date,
		enrol_week numeric,
		enrolled_ahc numeric,
		enrolment_activity_end_date date,
		entitlement_contract_description text,
		fee_catagory text,
		grade text,
		grade_keyed text,
		granted_date date,
		hecs_payment_option text,
		hecs_payment_option_code text,
		highest_prior_education_level_completed text,
		highest_prior_education_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		home_language_code text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		language text,
		level text,
		mobile_phone_number text,
		no_course_intention text,
		not_approved_date date,
		outcome text,
		override_activity_end_date date,
		override_activity_start_date date,
		postal_postcode text,
		residential_postcode text,
		result_date date,
		result_type text,
		result_week numeric,
		resulted_ahc numeric,
		sca_funding_source text,
		staff_indicator text,
		stream_code text,
		student_first_name text,
		student_gender text,
		student_home_state text,
		student_id text,
		student_last_name text,
		study_reason text,
		study_reason_description text,
		tci text,
		teaching_period text,
		teaching_period_end_date text,
		unit_attempt_status text,
		unit_census_date date,
		unit_code text,
		unit_contact text,
		unit_delivery_location text,
		unit_delivery_type text,
		unit_funding_source text,
		unit_name text,
		unit_student_status text,
		unit_student_status_code text,
		ur_outcome text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE team_activity (
		unit_delivery_team text,
		division text,
		funding_source text,
		contract_course text,
		contract_course_name text,
		total_target numeric,
		total_enrolled numeric,
		total_resulted numeric,
		location text,
		remoteness text,
		urban_target numeric,
		urban_enrolled numeric,
		urban_resulted numeric,
		regional_target numeric,
		regional_enrolled numeric,
		regional_resulted numeric,
		remote_target numeric,
		remote_enrolled numeric,
		remote_resulted numeric,
		interstate_target numeric,
		interstate_enrolled numeric,
		interstate_resulted numeric
	)
	""",
	"""
	CREATE TABLE unresulted_sua_2017 (
		contract_team text,
		course_code text,
		course_name text,
		course_admin_team text,
		enrolled_ahc numeric,
		grade text,
		enrolment_activity_end_date date,
		result_type text,
		sca_funding_source text,
		student_first_name text,
		student_id text,
		student_last_name text,
		teaching_period text,
		unit_attempt_status text,
		unit_code text,
		unit_delivery_location text,
		unit_name text,
		usi_flag text
	) 
	""",
	"""
	CREATE TABLE vet_apprentice (
		person_id text,
		api_id text,
		api_type text,
		course_code text,
		api_start_date text,
		api_end_date text,
		funding_source text,
		unit_cd text,
		unit_act_end_date text,
		enr_act_end_dte text,
		addr_type text,
		addr_start_date text,
		addr_end_date text,
		addr_line1 text,
		addr_line2 text,
		addr_line3 text,
		addr_line4 text,
		addr_line5 text,
		addr_aust_postcode text,
		other_details text,
		phone_3 text,
		phone_2 text,
		phone_1 text
	)
	""",
	"""
	CREATE TABLE vet_course_completions (
		student_id text,
		student_last_name text, 
		student_first_name text,
		student_gender text,
		student_dob date,
		student_email_address text,
		course_code text,
		course_name text,
		course_commencement_date date,
		course_attempt_status text,
		course_requirements_completed_date date,
		sca_funding_source text,
		course_admin_location text,
		course_admin_team text,
		course_delivery_mode text,
		study_reason text,
		vet_in_school_indicator text,
		unit_only_enrolment_indicator text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		residential_postcode text,
		home_language_code text,
		birth_country_code text,
		at_school_indicator text,
		atsi_status text,
		employment_category text,
		conferral_date date,
		vet_school_name text,
		no_course_intention text,
		chessn text,
		vfh_atsi_code text,
		vfh_citizenship_code text,
		vfh_birth_country_code text,
		vfh_home_language_code text,
		vfh_term_location_postcode text,
		vfh_term_location_country_code text,
		vfh_home_location_postcode text,
		vfh_home_location_country_code text,
		vfh_arrival_year text,
		vfh_permanent_resident_code text,
		vfh_commencing_location_postcode text,
		vfh_commencing_geographic_location text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_year text,
		basis_for_admission_code text,
		hecs_payment_option_code text,
		usi_flag text,
		entitlement_contract_description text
	)
	""",
	"""
	CREATE TABLE vet_course_completions_2018 (
		at_school_indicator text,
		atsi text,
		basis_for_admission_code text,
		birth_country_code text,
		chessn text,
		conferral_date date,
		course_admin_location text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_name text,
		course_requirements_completed_date date,
		employment_category text,
		employment_category_description text,
		entitlement_contract_description text,
		hecs_payment_option_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		home_language_code text,
		no_course_intention text,
		residential_postcode text,
		sca_funding_source text,
		student_dob date,
		student_email_address text,
		student_first_name text,
		student_gender text,
		student_id text,
		student_last_name text,
		study_reason text,
		study_reason_description text,
		unit_only_enrolment_indicator text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_description text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE vfh_unit_attempts (
		teaching_period text,
		student_id text,
		course_admin_team text,
		unit_delivery_location text,
		unit_delivery_remoteness text,
		delivery_location_team text,
		unit_funding_source text,
		course_delivery_mode text,
		course_code text,
		fee_category text,
		course_name text,
		unit_code text,
		unit_name text,
		enrolled_ahc numeric,
		resulted_ahc numeric,
		grade text,
		atsi text,
		course_industry text,
		student_last_name text,
		student_first_name text,
		aci text,
		tci text,
		student_dob date,
		override_activity_end_date date,
		unit_attempt_status text,
		correspondence_category text,
		student_gender text,
		student_home_state text,
		grade_keyed text,
		deceased_indicator text,
		vet_school_name text,
		unit_delivery_type text,
		enrol_date date,
		disc_date date,
		result_date date,
		staff_indicator text,
		stream_code text,
		study_reason text,
		granted_date date,
		vet_in_school_indicator text,
		at_school_indicator text,
		highest_prior_education_level_completed_code text,
		home_language_code text,
		birth_country_code text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		residential_postcode text,
		employment_category text,
		disability_flag text,
		course_attempt_status text,
		course_commencement_date date,
		sca_funding_source text,
		enrolment_activity_end_date date,
		postal_postcode text,
		override_activity_start_date text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		no_course_intention text,
		course_requirements_completed_indicator text,
		course_requirements_completed_date date,
		result_type text,
		unit_contact text,
		cancelled_date date,
		not_approved_date date,
		administrative_unit_status text,
		chessn text,
		vfh_atsi_code text,
		vfh_citizenship_code text,
		vfh_birth_country_code text,
		vfh_home_language_code text,
		vfh_term_location_postcode text,
		vfh_term_location_country_code text,
		vfh_home_location_postcode text,
		vfh_home_location_country_code text,
		vfh_arrival_year text,
		vfh_permanent_resident_code text,
		vfh_commencing_location_postcode text,
		vfh_commencing_geographic_location text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_year text,
		basis_for_admission_code text,
		hecs_payment_option_code text,
		unit_student_status_code text,
		unit_census_date date,
		contract_course_unit_name text,
		contract_course_unit_code text,
		contract text,
		outcome text,
		age numeric,
		teaching_period_end_date date,
		enrol_week numeric,
		result_week numeric,
		contract_team text,
		ur_outcome text
	)
	""",
	"""
	CREATE TABLE weekly_2017 (
		teaching_period text,
		student_id text,
		course_admin_team text,
		unit_delivery_location text,
		delivery_location_team text,
		unit_funding_source text,
		course_delivery_mode text,
		course_code text,
		fee_category text,
		course_name text,
		unit_code text,
		unit_name text,
		enrolled_ahc numeric,
		resulted_ahc numeric,
		grade text,
		atsi text,
		course_industry text,
		student_last_name text,
		student_first_name text,
		aci text,
		tci text,
		student_dob date,
		override_activity_end_date date,
		unit_attempt_status text,
		correspondence_category text,
		student_gender text,
		student_home_state text,
		grade_keyed text,
		vet_school_name text,
		unit_delivery_type text,
		enrol_date date,
		disc_date date,
		result_date date,
		staff_indicator text,
		stream_code text,
		study_reason text,
		granted_date date,
		vet_in_school_indicator text,
		at_school_indicator text,
		highest_prior_education_level_completed_code text,
		home_language_code text,
		birth_country_code text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		residential_postcode text,
		employment_category text,
		disability_flag text,
		course_attempt_status text,
		course_commencement_date date,
		sca_funding_source text,
		enrolment_activity_end_date date,
		postal_postcode text,
		override_activity_start_date date,
		intention_to_complete_course text,
		intention_to_complete_unit_only text,
		no_course_intention text,
		course_requirements_completed_indicator text,
		course_requirements_completed_date text,
		result_type text,
		unit_contact text,
		cancelled_date date,
		not_approved_date date,
		administrative_unit_status text,
		chessn text,
		vfh_atsi_code text,
		vfh_citizenship_code text,
		vfh_birth_country_code text,
		vfh_home_language_code text,
		vfh_term_location_postcode text,
		vfh_term_location_country_code text,
		vfh_home_location_postcode text,
		vfh_home_location_country_code text,
		vfh_arrival_year text,
		vfh_permanent_resident_code text,
		vfh_commencing_location_postcode text,
		vfh_commencing_geographic_location text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_year text,
		basis_for_admission_code text,
		hecs_payment_option_code text,
		unit_student_status_code text,
		unit_census_date date,
		usi_flag text,
		deceased_indicator text,
		entitlement_contract_description text,
		email_address text,
		mobile_phone_number text,
		contract_course_unit_name text,
		contract_course_unit_code text,
		contract text,
		outcome text,
		age numeric,
		teaching_period_end_date date,
		enrol_week numeric,
		result_week numeric,
		contract_team text,
		ur_outcome text
	)
	""",
	"""
	CREATE TABLE weekly_current (
		teaching_period text,
		student_id text,
		course_admin_team text,
		unit_delivery_location text,
		delivery_location_team text,
		unit_funding_source text,
		course_delivery_mode text,
		course_code text,
		fee_category text,
		course_name text,
		unit_code text,
		unit_name text,
		enrolled_ahc numeric,
		resulted_ahc numeric,
		grade text,
		atsi text,
		course_industry text,
		student_last_name text,
		student_first_name text,
		aci text,
		tci text,
		student_dob date,
		override_activity_end_date date,
		unit_attempt_status text,
		correspondence_category text,
		student_gender text,
		student_home_state text,
		grade_keyed text,
		vet_school_name text,
		unit_delivery_type text,
		enrol_date date,
		disc_date date,
		result_date date,
		staff_indicator text,
		stream_code text,
		study_reason text,
		granted_date date,
		vet_in_school_indicator text,
		at_school_indicator text,
		highest_prior_education_level_completed_code text,
		home_language_code text,
		birth_country_code text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		residential_postcode text,
		employment_category text,
		disability_flag text,
		course_attempt_status text,
		course_commencement_date date,
		sca_funding_source text,
		enrolment_activity_end_date date,
		postal_postcode text,
		override_activity_start_date date,
		intention_to_complete_course text,
		intention_to_complete_unit_only text,
		no_course_intention text,
		course_requirements_completed_indicator text,
		course_requirements_completed_date date,
		result_type text,
		unit_contact text,
		cancelled_date date,
		not_approved_date date,
		administrative_unit_status text,
		chessn text,
		vfh_atsi_code text,
		vfh_citizenship_code text,
		vfh_birth_country_code text,
		vfh_home_language_code text,
		vfh_term_location_postcode text,
		vfh_term_location_country_code text,
		vfh_home_location_postcode text,
		vfh_home_location_country_code text,
		vfh_arrival_year text,
		vfh_permanent_resident_code text,
		vfh_commencing_location_postcode text,
		vfh_commencing_geographic_location text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_year text,
		basis_for_admission_code text,
		hecs_payment_option_code text,
		unit_student_status_code text,
		unit_census_date date,
		usi_flag text,
		deceased_indicator text,
		entitlement_contract_description text,
		email_address text,
		mobile_phone_number text,
		contract_course_unit_name text,
		contract_course_unit_code text,
		contract text,
		outcome text,
		age numeric,
		teaching_period_end_date date,
		enrol_week numeric,
		result_week numeric,
		contract_team text,
		ur_outcome text
	)
	""",
	"""
	CREATE TABLE xlookup_activity_pattern_trend (
		unit_delivery_team text,
		division text,
		funding_source text,
		week_2018 numeric,
		week_2017 numeric,
		target_2018 numeric,
		target_2017 numeric,
		enrolled_2018 numeric,
		resulted_2018 numeric,
		funded_enrolled_2018 numeric,
		funded_resulted_2018 numeric,
		unfunded_enrolled_2018 numeric,
		unfunded_resulted_2018 numeric,
		enrolled_2017 numeric,
		resulted_2017 numeric,
		funded_enrolled_2017 numeric,
		funded_resulted_2017 numeric,
		unfunded_enrolled_2017 numeric,
		unfunded_resulted_2017 numeric
	)
	""",
	"""
	CREATE TABLE xlookup_afb_course_table (
		course_code text,
		course_name text
	)
	""",
	"""
	CREATE TABLE xlookup_age_group (
		age numeric,
		age_range text
	)
	""",
	"""
	CREATE TABLE xlookup_australia_post (
		pcode text,
		locality text,
		state text,
		comments text,
		deliveryoffice text,
		presortindicator text,
		parcelzone text,
		bspnumber text,
		bspname text,
		category text
	)
	""",
	"""
	CREATE TABLE xlookup_country (
		identifier text,
		full_name text,
		last_updated date
	)
	""",
	"""
	CREATE TABLE xlookup_course (
		code text,
		description text,
		active_indicator text,
		code_reference text,
		description_reference text,
		level text,
		foe2 text,
		foe4 text,
		anzsco text,
		industry text
	)
	""",
	"""
	CREATE TABLE xlookup_det_industry (
		code text,
		description text
	)
	""",
	"""
	CREATE TABLE xlookup_division (
		team_code text,
		division text
	)
	""",
	"""
	CREATE TABLE xlookup_employment_status (
		employment_status_code text,
		employment_status_description text
	)
	""",
	"""
	CREATE TABLE xlookup_etp_eligible_course_list (
		course_code text,
		course_name text,
		units_to_complete numeric,
		price_urban numeric,
		price_regional numeric,
		price_remote numeric
	)
	""",
	"""
	CREATE TABLE xlookup_etp_eligible_course_list_by_contract (
		course_code text,
		course_name text,
		purchasing_contract_identifier text
	)
	""",
	"""
	CREATE TABLE xlookup_etp_targets (
		division text,
		unit_delivery_team text,
		team_target_ahc numeric,
		team_target_headcount numeric
	)
	""",
	"""
	CREATE TABLE xlookup_etp_targets_2016 (
		division text,
		unit_delivery_team text,
		division_target_ahc numeric
	)
	""",
	"""
	CREATE TABLE xlookup_etp_targets_2017 (
		division text,
		unit_delivery_team text,
		team_target_ahc numeric,
		team_target_headcount numeric
	)
	""",
	"""
	CREATE TABLE xlookup_FOE2 (
		code text,
		description text
	)
	""",
	"""
	CREATE TABLE xlookup_FOE4 (
		code text,
		description text	
	)
	""",
	"""
	CREATE TABLE xlookup_language (
		identifier text,
		full_name text,
		last_updated date
	)
	""",
	"""
	CREATE TABLE xlookup_level (
		level_code text,
		description text
	)
	""",
	"""
	CREATE TABLE xlookup_location (
		code text,
		description text,
		postal_location text,
		profile_location text,
		region text,
		remoteness text,
		providence text,
		postcode text,
		state_code text
	)
	""",
	"""
	CREATE TABLE xlookup_mceetya_ses (
		postcode text,
		state text,
		a_ses text,
		s_ses text,
		m1 numeric,
		m2 numeric,
		m3 numeric,
		m4 numeric,
		m5 numeric,
		m6 numeric,
		m7 numeric,
		m8 numeric,
		m9 numeric,
		m_total numeric,
		a_ses2006 text,
		s_ses2006 text
	)
	""",
	"""
	CREATE TABLE xlookup_nits_superseded_unit (
		identifier text,
		short_name text,
		superseding_identifier text,
		superseding_short_name text,
		description text,
		last_update date
	)
	""",
	"""
	CREATE TABLE xlookup_nits_superseded_unit_equivalent_flag (
		identifier text,
		short_name text,
		superseding_identifier text,
		superseding_short_name text,
		description text,
		last_update date,
		equivalent text
	)
	""",
	"""
	CREATE TABLE xlookup_prior_education_level (
		level_code text,
		description text
	)
	""",
	"""
	CREATE TABLE xlookup_school_level (
		school_level_code text,
		school_level_description text
	)
	""",
	"""
	CREATE TABLE xlookup_state_reference (
		state text,
		state_identifier text
	)
	""",
	"""
	CREATE TABLE xlookup_study_reason (
		study_reason_id text,
		study_reason_description text,
		current_2018 text,
		current_2017 text,
		current_2016 text,
		current_2015 text,
		current_2014 text,
		current_2013 text,
		current_2012 text,
		current_2011 text,
		current_2010 text,
		current_2009 text,
		current_2008 text
	)
	""",
	"""
	CREATE TABLE xlookup_target (
		contract_team text,
		division_school text,
		location text,
		region text,
		remoteness text,
		providence text,
		contract_unit text,
		contract_course_unit text,
		note text,
		funding text,
		source text,
		contract text,
		ahc numeric,
		course_orig text
	)
	""",
	"""
	CREATE TABLE xlookup_team (
		code text,
		description text,
		current_2018 text,
		current_2017 text,
		current_2016 text,
		current_2015 text,
		current_2014 text,
		current_2013 text,
		current_2012 text,
		current_2011 text,
		current_2010 text,
		current_2009 text,
		current_2008 text
	)
	""",
	"""
	CREATE TABLE xlookup_unit_delivery_type (
		code text,
		description text
	)
	""",
	"""
	CREATE TABLE xlookup_units (
		identifier text,
		full_name text,
		module_foe text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_atsi (
		vfh_atsi_code text,
		vfh_atsi_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_basis_for_admission (
		vfh_basis_for_admission_cd text,
		vfh_basis_for_admission_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_birth_country (
		vfh_birth_country_cd text,
		vfh_birth_country_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_citizenship (
		vfh_citizenship_cd text,
		vfh_citizenship_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_highest_attainment (
		vfh_highest_participation_cd text,
		vfh_highest_participation_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_language (
		vfh_home_language_cd text,
		vfh_home_language_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_permanent_residence (
		vfh_permanent_residence_cd text,
		vfh_permanent_residence_description text
	)
	""",
	"""
	CREATE TABLE xlookup_vfh_student_status (
		vfh_student_status_cd text,
		vfh_student_status_description text
	)
	""",
	"""
	CREATE TABLE xref_activity_pattern_trend_template (
		unit_delivery_team text,
		division text,
		funding_source text,
		week_2018 numeric,
		week_2017 numeric,
		target_2018 numeric,
		target_2017 numeric,
		enrolled_2018 numeric,
		resulted_2018 numeric,
		funded_enrolled_2018 numeric,
		funded_resulted_2018 numeric,
		unfunded_enrolled_2018 numeric,
		unfunded_resulted_2018 numeric,
		enrolled_2017 numeric,
		resulted_2017 numeric,
		funded_enrolled_2017 numeric,
		funded_resulted_2017 numeric,
		unfunded_enrolled_2017 numeric,
		unfunded_resulted_2017 numeric
	)
	""",
	"""
	CREATE TABLE xref_apprentice_course (
		course_admin_team text,
		student_id text,
		atsi text,
		age_range text,
		disability_flag text,
		employment_category text,
		employment_category_description text,
		residential_postcode text,
		highest_school_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		country_of_birth text,
		language text,
		highest_prior_education_level_completed text,
		at_school_indicator text,
		industry text,
		foe2 text,
		foe4 text,
		course_level_description text,
		course_code text,
		course_name text,
		unit_funding_source text,
		tci text,
		tci_start_date text,
		tci_end_date text,
		sum_of_enrolled_ahc numeric,
		sum_of_resulted_ahc numeric,
		address_start_date text,
		address_end_date text,
		employer_or_business_name text,
		employer_address_line_1 text,
		employer_address_line_2 text,
		employer_suburb text,
		employer_state text,
		employer_postcode text,
		employer_phone_number text,
		employer_fax_number text,
		employer_contact_name text,
		employer_email_details text
	)
	""",
	"""
	CREATE TABLE xref_apprentice_sua (
		delivery_location_team text,
		student_id text,
		atsi text,
		age_range text,
		disability_flag text,
		employment_category text,
		employment_category_description text,
		residential_postcode text,
		highest_school_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		country_of_birth text,
		language text,
		highest_prior_education_level_completed text,
		at_school_indicator text,
		vet_in_school_indicator text,
		course_industry text,
		course_industry_name text,
		foe2 text,
		foe4 text,
		course_level_description text,
		course_code text,
		unit_code text,
		fee_catagory text,
		unit_funding_source text,
		grade text,
		unit_delivery_location text,
		enrol_date date,
		result_date date,
		tci text,
		tci_start_date text,
		tci_end_date text,
		enrolled_ahc numeric,
		resulted_ahc numeric
	)
	""",
	"""
	CREATE TABLE xref_error_for_correction_template (
		error_type text,
		course_admin_team text,
		delivery_location_team text,
		teaching_period text,
		student_id text,
		student_last_name text,
		student_first_name text,
		atsi text,
		gender text,
		dob date,
		deceased_indicator text,
		disability text,
		home_language_code text,
		birth_country_code text,
		residential_post_code text,
		home_state text,
		prior_education text,
		employment_category text,
		at_school_indicator text,
		vet_in_school_indicator text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		age_highest_school_completed text,
		course_code text,
		unit_code text,
		unit_funding_source text,
		enrol_date date,
		outcome text,
		unit_attempt_status text,
		study_reason text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		no_course_intention text,
		total_lrnsupp_ahc text,
		total_enrolled_ahc text,
		granted_date date,
		cancelled_date date,
		not_approved_date date,
		usi_flag text,
		entitlement_contract_description text,
		course_commencement_date date,
		course_attempt_status text
	)
	""",
	"""
	CREATE TABLE xref_student_course_attempt_template (
		a_ses2006 text,
		age numeric,
		age_range text,
		at_school_indicator text,
		atsi text,
		basis_for_admission text,
		basis_for_admission_code text,
		birth_country text,
		chessn text,
		contract_team text,
		correspondence_category text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_name text,
		course_requirements_completed_date date,
		course_requirements_completed_indicator text,
		deceased_indicator text,
		division text,
		email_address text,
		enrolled_ahc_ex_ns_ct_sw numeric,
		entitlement_contract_description text,
		fee_category text,
		foe2 text,
		foe4 text,
		hecs_payment_option text,
		hecs_payment_option_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		industry text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		level text,
		mobile_phone_number text,
		no_course_intention text,
		postal_postcode text,
		residential_postcode text,
		resulted_ahc_ex_ns_ct_sw numeric,
		sca_funding_source text,
		student_gender text,
		student_home_state text,
		student_id text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE xref_student_template (
		a_ses2006 text,
		age numeric,
		age_range text,
		atsi text,
		chessn text,
		country_of_birth text,
		deceased_indicator text,
		disability_flag text,
		dob date,
		email_address text,
		employment_category text,
		enrolled_ahc_ex_ns_ct_sw numeric,
		equivalent_eftsl numeric,
		ft_pt_status text,
		highest_prior_education_level_completed text,
		highest_school_level_completed text,
		highest_school_level_completed_year text,
		language text,
		mobile_phone_number text,
		postal_postcode text,
		residential_postcode text,
		resulted_ahc_ex_ns_ct_sw numeric,
		student_first_name text,
		student_gender text,
		student_home_state text,
		student_id text,
		student_last_name text,
		usi_flag text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE xref_student_unit_attempt_template (
		a_ses2006 text,
		aci text,
		administrative_unit_status text,
		age numeric,
		at_school_indicator text,
		atsi text,
		basis_for_admission text,
		basis_for_admission_code text,
		birth_country_code text,
		cancelled_date date,
		chessn text,
		contract text,
		contract_course_unit_code text,
		contract_course_unit_name text,
		contract_team text,
		correspondence_category text,
		country_of_birth text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_industry text,
		course_industry_name text,
		course_name text,
		course_requirements_completed_date date,
		course_requirements_completed_indicator text,
		deceased_indicator text,
		delivery_location_team text,
		delivery_postal_location text,
		delivery_providence text,
		delivery_region text,
		delivery_remoteness text,
		delivery_state_code text,
		disability_flag text,
		disc_date date,
		division text,
		email_address text,
		employment_category text,
		employment_category_description text,
		enrol_date date,
		enrol_week numeric,
		enrolled_ahc numeric,
		enrolment_activity_end_date date,
		entitlement_contract_description text,
		fee_catagory text,
		grade text,
		grade_keyed text,
		granted_date date,
		hecs_payment_option text,
		hecs_payment_option_code text,
		highest_prior_education_level_completed text,
		highest_prior_education_level_completed_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		home_language_code text,
		intention_to_complete_course text,
		intention_to_complete_units_only text,
		language text,
		level text,
		mobile_phone_number text,
		no_course_intention text,
		not_approved_date date,
		outcome text,
		override_activity_end_date date,
		override_activity_start_date date,
		postal_postcode text,
		residential_postcode text,
		result_date date,
		result_type text,
		result_week numeric,
		resulted_ahc numeric,
		sca_funding_source text,
		staff_indicator text,
		stream_code text,
		student_first_name text,
		student_gender text,
		student_home_state text,
		student_id text,
		student_last_name text,
		study_reason text,
		study_reason_description text,
		tci text,
		teaching_period text,
		teaching_period_end_date text,
		unit_attempt_status text,
		unit_census_date date,
		unit_code text,
		unit_contact text,
		unit_delivery_location text,
		unit_delivery_type text,
		unit_funding_source text,
		unit_name text,
		unit_student_status text,
		unit_student_status_code text,
		ur_outcome text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_decription text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE xref_team_activity (
		unit_delivery_team text,
		division text,
		funding_source text,
		contract_course text,
		contract_course_name text,
		total_target numeric,
		total_enrolled numeric,
		total_resulted numeric,
		location text,
		remoteness text,
		urban_target numeric,
		urban_enrolled numeric,
		urban_resulted numeric,
		regional_target numeric,
		regional_enrolled numeric,
		regional_resulted numeric,
		remote_target numeric,
		remote_enrolled numeric,
		remote_resulted numeric,
		interstate_target numeric,
		interstate_enrolled numeric,
		interstate_resulted numeric
	)
	""",
	"""
	CREATE TABLE xref_unresulted_sua_2017 (
		contract_team text,
		course_code text,
		course_name text,
		course_admin_team text,
		enrolled_ahc numeric,
		grade text,
		enrolment_activity_end_date date,
		result_type text,
		sca_funding_source text,
		student_first_name text,
		student_id text,
		student_last_name text,
		teaching_period text,
		unit_attempt_status text,
		unit_code text,
		unit_delivery_location text,
		unit_name text,
		usi_flag text
	)
	""",
	"""
	CREATE TABLE xref_vet_course_completions_2018 (
		at_school_indicator text,
		atsi text,
		basis_for_admission_code text,
		birth_country_code text,
		chessn text,
		conferral_date date,
		course_admin_location text,
		course_admin_team text,
		course_attempt_status text,
		course_code text,
		course_commencement_date date,
		course_delivery_mode text,
		course_name text,
		course_requirements_completed_date date,
		employment_category text,
		employment_category_description text,
		entitlement_contract_description text,
		hecs_payment_option_code text,
		highest_school_level_completed text,
		highest_school_level_completed_code text,
		highest_school_level_completed_year text,
		home_language_code text,
		no_course_intention text,
		residential_postcode text,
		sca_funding_source text,
		student_dob date,
		student_email_address text,
		student_first_name text,
		student_gender text,
		student_id text,
		student_last_name text,
		study_reason text,
		study_reason_description text,
		unit_only_enrolment_indicator text,
		usi_flag text,
		vet_in_school_indicator text,
		vet_school_name text,
		vfh_arrival_year text,
		vfh_atsi_code text,
		vfh_atsi_description text,
		vfh_birth_country_code text,
		vfh_birth_country_description text,
		vfh_citizenship_code text,
		vfh_citizenship_description text,
		vfh_commencing_geographic_location text,
		vfh_commencing_location_postcode text,
		vfh_highest_attainment_code text,
		vfh_highest_attainment_description text,
		vfh_highest_attainment_year text,
		vfh_home_language_code text,
		vfh_home_language_description text,
		vfh_home_location_country_code text,
		vfh_home_location_country_description text,
		vfh_home_location_postcode text,
		vfh_permanent_resident_code text,
		vfh_permanent_resident_status text,
		vfh_term_location_country_code text,
		vfh_term_location_country_description text,
		vfh_term_location_postcode text
	)
	""",
	"""
	CREATE TABLE xref_vfh_unit_tp (
		course text,
		status text,
		course_name text,
		location text,
		unit text,
		unit_name text,
		hrs text,
		eftsl text,
		ntg_tuition text,
		ntg_rpl text,
		full_fee text,
		sponsored_full_fee text,
		sponsored_rpl_fee text,
		rpl_fee text,
		start_date text,
		teaching_period text,
		rpl_only text,
		end_date text,
		census_date text,
		team text,
		duration text,
		full_fee_est_cost text,
		subsidised_est_cost text,
		delivery text,
		est_sponsored_cost text
	)
	"""]